apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: terraform-aks-cluster-rg
    service.beta.kubernetes.io/azure-load-balancer-public-ip: sd-public-ip
spec:
  type: LoadBalancer
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
